In [1]:
import scanpy as sc  
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl 
import cell2location 
import pandas as pd
import torch 
import os
pd.set_option('display.max_columns',400)
pd.set_option('display.max_categories',40)
plt.rcParams['pdf.fonttype'] = 42

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
h5ad_dir = "ann_finest_level/h5ad"
os.makedirs(h5ad_dir, exist_ok=True)

In [4]:
adata_vis = sc.read_h5ad("/Users/jk/Documents/Lab2/visium/python_analysis/local_401/h5ad/adata_vis_assigned_cell_types_ann_finest_level.h5ad")

In [5]:
adata_vis.obs

,in_tissue,array_row,array_col,library_id,alignment,desired_rc,actual_rc,xmin,xmax,ymin,ymax,hpx,vpx,slide,area,date,cytassist_ver,seq_batch,probe_date,probe_lot,probe_group,cond,cond_rep,rep,age,sex,bmi,packyears,FVC,DLCO,6MWD,outcome_long,tte_long,outcome_24m,tte_24m,lobe_lr,lobe,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,total_counts_ribo,log1p_total_counts_ribo,pct_counts_ribo,total_counts_hb,log1p_total_counts_hb,pct_counts_hb,n_counts,n_genes,training_batch,AT0,AT1,AT2,AT2 proliferating,Adventitial fibroblasts,Alveolar Mph CCL3+,Alveolar Mph MT-positive,Alveolar Mph proliferating,Alveolar fibroblasts,Alveolar macrophages,B cells,Basal resting,CD4 T cells,CD8 T cells,Classical monocytes,Club (nasal),Club (non-nasal),DC1,DC2,Deuterosomal,EC aerocyte capillary,EC arterial,EC general capillary,EC venous pulmonary,EC venous systemic,Goblet (bronchial),Goblet (nasal),Goblet (subsegmental),Hillock-like,Interstitial Mph perivascular,Ionocyte,Lymphatic EC differentiating,Lymphatic EC mature,Mast cells,Mesothelium,Migratory DCs,Monocyte-derived Mph,Multiciliated (nasal),Multiciliated (non-nasal),Myofibroblasts,NK cells,Neuroendocrine,Non-classical monocytes,Peribronchial fibroblasts,Pericytes,Plasma cells,Plasmacytoid DCs,SM activated stress response,SMG duct,Smooth muscle,Smooth muscle FAM83D+,Subpleural fibroblasts,Suprabasal,T cells proliferating,Unknown,pre-TB secretory,cell_type_assigned
AACACGTGCATCGCAC-1-18_57617_A1,1.0,76.0,22.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3961,8.284504,7804.0,8.962520,31.765761,35.212711,39.928242,49.410559,629.0,6.445720,8.059970,0.0,0.0,0.0,0.0,0.0,0.0,7804.0,3961,0,0.000967,0.000081,0.000023,0.000279,0.234594,0.009023,0.003434,0.045472,0.387183,0.001108,3.730742,0.001663,0.065855,0.019768,0.004821,0.127872,0.000417,0.008481,0.040385,0.010641,0.001719,0.002331,0.000529,0.001759,0.004936,0.001933,0.000464,0.042375,0.002770,0.058909,0.003027,0.003101,0.008538,0.003847,0.000322,0.044897,0.017594,0.026567,0.000907,0.003966,0.016523,0.092378,0.008129,0.037726,0.014092,0.968134,0.362111,0.025284,0.008943,0.038652,0.060598,0.231837,0.004889,0.044583,0.001354,0.000324,B cells
AACACTTGGCAAGGAA-1-18_57617_A1,1.0,47.0,71.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3322,8.108623,5412.0,8.596559,15.909091,20.842572,27.475979,40.742794,280.0,5.638355,5.173688,0.0,0.0,0.0,0.0,0.0,0.0,5412.0,3322,0,0.137828,0.802715,0.341800,0.009572,0.139944,0.039461,0.032829,0.186727,0.888112,0.481472,0.039227,0.013804,0.056936,0.042788,0.031012,0.009081,0.043570,0.023910,0.040213,0.001578,1.365678,0.136504,0.618607,0.156473,0.098999,0.008318,0.010266,0.010062,0.009213,0.056085,0.024774,0.080588,0.040189,0.030853,0.005049,0.038562,0.017642,0.068411,0.598156,0.124178,0.036192,0.026985,0.061592,0.055564,0.479931,0.034395,0.011473,0.129968,0.007446,0.244876,0.049037,0.007688,0.022190,0.089888,0.012039,0.379554,EC aerocyte capillary
AACAGGATTCATAGTT-1-18_57617_A1,1.0,49.0,43.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2120,7.659643,3313.0,8.105911,26.048898,30.878358,37.488681,51.101720,538.0,6.289716,16.239059,0.0,0.0,0.0,0.0,0.0,0.0,3313.0,2120,0,0.005170,0.059832,0.082329,0.001831,0.001260,0.013375,0.011541,0.018772,0.068402,0.020841,0.011103,0.004326,0.079482,0.039857,0.005894,0.012759,0.000413,0.376290,0.007926,0.002451,1.006702,0.058915,2.460315,0.390035,0.384114,0.002900,0.001124,0.012576,0.005301,0.008660,0.003291,0.010103,0.009291,0.070889,0.000651,0.026347,0.006695,0.001637,0.001180,0.004225,0.024105,0.055135,0.015300,0.071425,0.144042,0.012755,0.018465,0.034665,0.005432,0.011212,0.009665,0.028604,0.002229,0.021346,0.002790,0.000472,EC general capillary
AACAGGTTCACCGAAG-1-18_57617_A1,1.0,51.0,41.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2388,7.778630,3665.0,8.206857,25.702592,29.795362,35.470668,48.485675,697.0,6.548219,19.017735,0.0,0.0,0.0,0.0,0.0,0.0,3665.0,2388,1,0.001563,0.020343,0.057659,0.001120,0.005092,0.002046,0.005805,0.000767,0.061047,0.002963,0.117381,0.004090,0.077575,0.054498,0.028830,0.167655,0.000468,0.001589,0.012085,0.020475,0.162310,0.051763,2.538344,0.109793,0.134852,0.001277,0.000667,0.001587,0.007030,0.016640,0.003956,0.062362,0.013975,0.012171,0.001957,0.069829,0.010399,0.113839,0.003326,0.003756,0.046806,0.004957,0.011046,0.015874,0.085721,0.021336,0.006211,0.002165,0.172565,0.029759,0.001750,0.015225,0.002373,0.085016,0.002622,0.000468,EC general capillary
AACAGTCAGGCTCCGC-1-18_57617_A1,1.0,24.0,6.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,4939,8.505121,10317.0,9.241645,17.514781,22.545314,28.777745,40.544732,498.0,6.212606,4.826984,0.0,0.0,0.0,0.0,0.0,0.0,10317.0,4939,1,0.571262,0.794535,0.611508,0.019281,0.012665,0.101478,0.013556,0.016001,0.026405,0.450508,0.019763,0.977336,0.043126,0.032375,0.010553,0.033321,0.003311,0.055528,0.082817,0.013789,0.064305,0.007815,0.053782,0.002625,0.002509,0.011348,0.336812,0.006089,0.754471,0.345387,0.042870,0.015813,0.003935,0.003842,0.003417,0.006994,1.927120,0.014479,0.006172,0.104371,0.041883,0.010310,0.027616,0.826019,0.035608,0.000658,0.007651,0.000577,0.005258,0.064397,0.001486,0.004463,0.031568,0.004771,0.007579,0.018862,Monocyte-derived Mph
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGTTCATTGGTCCAAG-1-22_16220_B1,1.0,55.0,99.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,7129,8.872067,19251.0,9.865370,16.149810,20.637889,26.414212,37.296764,781.0,6.661855,4.056932,0.0,0.0,0.0,0.0,0.0,0.0,19251.0,7129,1,0.367223,2.524808,4.255534,0.157300,0.003124,0.119464,0.055409,0.065133,1.719185,0.480502,0.182870,0.047675,0.994454,0.724625,0.103567,0.079388,0.028916,0.097227,0.212938,0.001171,3.753310,0.227036,2.941121,0.053537,0.037008,0.047620,0.069989,0.071654,0.015006,0.810489,0.170295,0.329601,0.037099,0.113724,0.007770,0.183838,0.055765,0.102231,0.001477,0.592959,0.413240,0.058103,0.221728,0.352980,1.715962,0.041914,0.081070,0.004009,0.007826,0.010457,0.007975,0.049609,0.025066,0.487826,0.039088,0.013980,AT2
TGTTGCGTCCAAGATT-1-22_16220_B1,1.0,51.0,65.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3768,8.234565,7184.0,8.879751,19.724388,24.972160,31.556236,44.863586,362.0,5.894403,5.038976,0.0,0.0,0.0,0.0,0.0,0.0,7184.0,3768,1,0.042970,3.252706,0.800204,0.078585,0.015209,0.153775,0.020274,0.010831,0.638489,0.195006,0.057860,0.009325,0.098929,0.061988,0.016352,0.011592,0.009237,0.067379,0.069889,0.003205,0.166659,0.043957,0.215042,0.018193,0.079329,0.009103,0.039361,0.030072,0.750197,0.257543,0.021430,0.029917,0.013606,0.071730,0.229185,0.116586,0.032344,0.007413,0.003729,0.041719,0.028020,0.014150,0.023068,0.424080,0.238952,0.216965,0.020822,0.001748,0.005828,0.004884,0.017080,0.007916,0.016669,0.119467,0.012833,0.009157,AT1
TGTTGGAAGCTCGGTA-1-22_16220_B1,1.0,1.0,95.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3776,8.236685,6059.0,8.709465,15.118006,19.590692,25.383727,37.629972,192.0,5.262690,3.168840,0.0,0.0,0.0,0.0,0.0,0.0,6059.0,3776,0,0.027733,0.414859,0.910561,0.122145,0.005666,0.042518,0.030576,0.015203,0.121399,0.098804,0.119536,0.024286,0.339794,0.091603,0.030221,0.278749,0.002894,0.241318,0.086295,0.001514,0.168115,0.014023,0.136537,0.006779,0.053962,0.006871,0.005770,0.006127,0.046612,0.231813,0.160615,0.016836,0.003369,0.005285,0.001335,0.043407,1.020134,0.102844,0.002140,0.007015,0.110815,0.026650,0.098955,0.383614,0.056468,0.404067,0.012163,0.000212,0.017786,0.003175,0.000582,0.104944,0.014785,0.132177,0.025317,0.009947,Monocyte-derived Mph
TGTTGGATGGACTTCT-1-22_16220_B1,1.0,13.0,53.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,2730,7.912423,4281.0,8.362176,19.504789,24.550339,31.558047,45.877132,284.0,5.652489,6.633964,0.0,0.0,0.0,0.0,0.0,0.0,4281.0,2730,1,0.072429,0.449036,2.438682,0.205547,0.017653,0.100401,0.037879,0.007400,0.128469,0.225288,0.050948,0.029965,0.082476,0.062304,0.020797,0.060529,0.005550,0.010314,0.036070,0.002774,0.178297,0.031913,0.181172,0.010522,0.009545,0.009999,0.009432,0.297448,0.014984,0.029476,0.042504,0.012411,0.017603,0.016918,0.014518,0.023244,0.161680,0.016316,0.013447,0.033981,0.072806,0.007954,0.021004,0.095104,0.053645,0.149471,0.096028,0.000275,0.040803,0.004464,0.001540,0.007772,0.032349,0.043325,0.016523,0.023343,AT2
TGTTGGCCAGACCTAC-1-22_16220_B1,1.0,49.0,47.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,4159,8.333270,7474.0,8.919319,15.948622,20.858978,27.588975,40.500401,300.0,5.707110,4.013915,0.0,0.0,0.0,0.0,0.0,0.0,7474.0,4159,1,0.794082,4.580537,0.870212,0.011166,0.003483,0.021490,0.007070,0.013400,0.337577,0.060844,0.055511,0.041338,0.130497,0.097034,0.022325,0.011413,0.001810,0.007699,0.045953,0.000505,0.302588,0.027830,0.324499,0.007028,0.010651,0.008317,0.005822,0.005205,0.085227,0.051932,0.031908,0.119128,0.018161,0.040580,0.001739,0.021628,0.025011,0.086345,0.001106,0.260140,0.065881,0.006617,0.038130,0.321881,0.190020,0.011823,0.009485,0.006947,0.004004,0.076724,0.088864,0.004982,0.012438,0.107862,0.007276,0.003487,AT1

In [7]:
adata_vis

AnnData object with n_obs × n_vars = 160702 × 16959
    obs: 'in_tissue', 'array_row', 'array_col', 'library_id', 'alignment', 'desired_rc', 'actual_rc', 'xmin', 'xmax', 'ymin', 'ymax', 'hpx', 'vpx', 'slide', 'area', 'date', 'cytassist_ver', 'seq_batch', 'probe_date', 'probe_lot', 'probe_group', 'cond', 'cond_rep', 'rep', 'age ', 'sex', 'bmi', 'packyears', 'FVC', 'DLCO', '6MWD', 'outcome_long', 'tte_long', 'outcome_24m', 'tte_24m', 'lobe_lr', 'lobe', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'n_counts', 'n_genes', 'training_batch', 'AT0', 'AT1', 'AT2', 'AT2 proliferating', 'Adventitial fibroblasts', 'Alveolar Mph CCL3+', 'Alveolar Mph MT-positive', 'Alveolar Mph proliferating', 'Alveolar fibroblasts', 'Alveolar macrophages', 'B cells', 'Basal resting', 'CD4 T cells', 'CD8 T cells', 'Classical monocytes', 'Club (nasal)', 'Club (non-nasal)', 'DC1', 'DC2', 'Deuterosomal', 'EC aerocyte capillary', 'EC arterial', 'EC general capillary', 'EC venous pulmonary', 'EC venous systemic', 'Goblet (bronchial)', 'Goblet (nasal)', 'Goblet (subsegmental)', 'Hillock-like', 'Interstitial Mph perivascular', 'Ionocyte', 'Lymphatic EC differentiating', 'Lymphatic EC mature', 'Mast cells', 'Mesothelium', 'Migratory DCs', 'Monocyte-derived Mph', 'Multiciliated (nasal)', 'Multiciliated (non-nasal)', 'Myofibroblasts', 'NK cells', 'Neuroendocrine', 'Non-classical monocytes', 'Peribronchial fibroblasts', 'Pericytes', 'Plasma cells', 'Plasmacytoid DCs', 'SM activated stress response', 'SMG duct', 'Smooth muscle', 'Smooth muscle FAM83D+', 'Subpleural fibroblasts', 'Suprabasal', 'T cells proliferating', 'Unknown', 'pre-TB secretory', 'cell_type_assigned'
    var: 'gene_ids'
    uns: 'mod_0', 'mod_1', 'spatial'
    obsm: 'MT', 'means_cell_abundance_w_sf', 'q05_cell_abundance_w_sf', 'q95_cell_abundance_w_sf', 'spatial', 'stds_cell_abundance_w_sf'

In [8]:
adata_vis.obs

,in_tissue,array_row,array_col,library_id,alignment,desired_rc,actual_rc,xmin,xmax,ymin,ymax,hpx,vpx,slide,area,date,cytassist_ver,seq_batch,probe_date,probe_lot,probe_group,cond,cond_rep,rep,age,sex,bmi,packyears,FVC,DLCO,6MWD,outcome_long,tte_long,outcome_24m,tte_24m,lobe_lr,lobe,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,total_counts_ribo,log1p_total_counts_ribo,pct_counts_ribo,total_counts_hb,log1p_total_counts_hb,pct_counts_hb,n_counts,n_genes,training_batch,AT0,AT1,AT2,AT2 proliferating,Adventitial fibroblasts,Alveolar Mph CCL3+,Alveolar Mph MT-positive,Alveolar Mph proliferating,Alveolar fibroblasts,Alveolar macrophages,B cells,Basal resting,CD4 T cells,CD8 T cells,Classical monocytes,Club (nasal),Club (non-nasal),DC1,DC2,Deuterosomal,EC aerocyte capillary,EC arterial,EC general capillary,EC venous pulmonary,EC venous systemic,Goblet (bronchial),Goblet (nasal),Goblet (subsegmental),Hillock-like,Interstitial Mph perivascular,Ionocyte,Lymphatic EC differentiating,Lymphatic EC mature,Mast cells,Mesothelium,Migratory DCs,Monocyte-derived Mph,Multiciliated (nasal),Multiciliated (non-nasal),Myofibroblasts,NK cells,Neuroendocrine,Non-classical monocytes,Peribronchial fibroblasts,Pericytes,Plasma cells,Plasmacytoid DCs,SM activated stress response,SMG duct,Smooth muscle,Smooth muscle FAM83D+,Subpleural fibroblasts,Suprabasal,T cells proliferating,Unknown,pre-TB secretory,cell_type_assigned
AACACGTGCATCGCAC-1-18_57617_A1,1.0,76.0,22.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3961,8.284504,7804.0,8.962520,31.765761,35.212711,39.928242,49.410559,629.0,6.445720,8.059970,0.0,0.0,0.0,0.0,0.0,0.0,7804.0,3961,0,0.000967,0.000081,0.000023,0.000279,0.234594,0.009023,0.003434,0.045472,0.387183,0.001108,3.730742,0.001663,0.065855,0.019768,0.004821,0.127872,0.000417,0.008481,0.040385,0.010641,0.001719,0.002331,0.000529,0.001759,0.004936,0.001933,0.000464,0.042375,0.002770,0.058909,0.003027,0.003101,0.008538,0.003847,0.000322,0.044897,0.017594,0.026567,0.000907,0.003966,0.016523,0.092378,0.008129,0.037726,0.014092,0.968134,0.362111,0.025284,0.008943,0.038652,0.060598,0.231837,0.004889,0.044583,0.001354,0.000324,B cells
AACACTTGGCAAGGAA-1-18_57617_A1,1.0,47.0,71.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3322,8.108623,5412.0,8.596559,15.909091,20.842572,27.475979,40.742794,280.0,5.638355,5.173688,0.0,0.0,0.0,0.0,0.0,0.0,5412.0,3322,0,0.137828,0.802715,0.341800,0.009572,0.139944,0.039461,0.032829,0.186727,0.888112,0.481472,0.039227,0.013804,0.056936,0.042788,0.031012,0.009081,0.043570,0.023910,0.040213,0.001578,1.365678,0.136504,0.618607,0.156473,0.098999,0.008318,0.010266,0.010062,0.009213,0.056085,0.024774,0.080588,0.040189,0.030853,0.005049,0.038562,0.017642,0.068411,0.598156,0.124178,0.036192,0.026985,0.061592,0.055564,0.479931,0.034395,0.011473,0.129968,0.007446,0.244876,0.049037,0.007688,0.022190,0.089888,0.012039,0.379554,EC aerocyte capillary
AACAGGATTCATAGTT-1-18_57617_A1,1.0,49.0,43.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2120,7.659643,3313.0,8.105911,26.048898,30.878358,37.488681,51.101720,538.0,6.289716,16.239059,0.0,0.0,0.0,0.0,0.0,0.0,3313.0,2120,0,0.005170,0.059832,0.082329,0.001831,0.001260,0.013375,0.011541,0.018772,0.068402,0.020841,0.011103,0.004326,0.079482,0.039857,0.005894,0.012759,0.000413,0.376290,0.007926,0.002451,1.006702,0.058915,2.460315,0.390035,0.384114,0.002900,0.001124,0.012576,0.005301,0.008660,0.003291,0.010103,0.009291,0.070889,0.000651,0.026347,0.006695,0.001637,0.001180,0.004225,0.024105,0.055135,0.015300,0.071425,0.144042,0.012755,0.018465,0.034665,0.005432,0.011212,0.009665,0.028604,0.002229,0.021346,0.002790,0.000472,EC general capillary
AACAGGTTCACCGAAG-1-18_57617_A1,1.0,51.0,41.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2388,7.778630,3665.0,8.206857,25.702592,29.795362,35.470668,48.485675,697.0,6.548219,19.017735,0.0,0.0,0.0,0.0,0.0,0.0,3665.0,2388,1,0.001563,0.020343,0.057659,0.001120,0.005092,0.002046,0.005805,0.000767,0.061047,0.002963,0.117381,0.004090,0.077575,0.054498,0.028830,0.167655,0.000468,0.001589,0.012085,0.020475,0.162310,0.051763,2.538344,0.109793,0.134852,0.001277,0.000667,0.001587,0.007030,0.016640,0.003956,0.062362,0.013975,0.012171,0.001957,0.069829,0.010399,0.113839,0.003326,0.003756,0.046806,0.004957,0.011046,0.015874,0.085721,0.021336,0.006211,0.002165,0.172565,0.029759,0.001750,0.015225,0.002373,0.085016,0.002622,0.000468,EC general capillary
AACAGTCAGGCTCCGC-1-18_57617_A1,1.0,24.0,6.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,4939,8.505121,10317.0,9.241645,17.514781,22.545314,28.777745,40.544732,498.0,6.212606,4.826984,0.0,0.0,0.0,0.0,0.0,0.0,10317.0,4939,1,0.571262,0.794535,0.611508,0.019281,0.012665,0.101478,0.013556,0.016001,0.026405,0.450508,0.019763,0.977336,0.043126,0.032375,0.010553,0.033321,0.003311,0.055528,0.082817,0.013789,0.064305,0.007815,0.053782,0.002625,0.002509,0.011348,0.336812,0.006089,0.754471,0.345387,0.042870,0.015813,0.003935,0.003842,0.003417,0.006994,1.927120,0.014479,0.006172,0.104371,0.041883,0.010310,0.027616,0.826019,0.035608,0.000658,0.007651,0.000577,0.005258,0.064397,0.001486,0.004463,0.031568,0.004771,0.007579,0.018862,Monocyte-derived Mph
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGTTCATTGGTCCAAG-1-22_16220_B1,1.0,55.0,99.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,7129,8.872067,19251.0,9.865370,16.149810,20.637889,26.414212,37.296764,781.0,6.661855,4.056932,0.0,0.0,0.0,0.0,0.0,0.0,19251.0,7129,1,0.367223,2.524808,4.255534,0.157300,0.003124,0.119464,0.055409,0.065133,1.719185,0.480502,0.182870,0.047675,0.994454,0.724625,0.103567,0.079388,0.028916,0.097227,0.212938,0.001171,3.753310,0.227036,2.941121,0.053537,0.037008,0.047620,0.069989,0.071654,0.015006,0.810489,0.170295,0.329601,0.037099,0.113724,0.007770,0.183838,0.055765,0.102231,0.001477,0.592959,0.413240,0.058103,0.221728,0.352980,1.715962,0.041914,0.081070,0.004009,0.007826,0.010457,0.007975,0.049609,0.025066,0.487826,0.039088,0.013980,AT2
TGTTGCGTCCAAGATT-1-22_16220_B1,1.0,51.0,65.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3768,8.234565,7184.0,8.879751,19.724388,24.972160,31.556236,44.863586,362.0,5.894403,5.038976,0.0,0.0,0.0,0.0,0.0,0.0,7184.0,3768,1,0.042970,3.252706,0.800204,0.078585,0.015209,0.153775,0.020274,0.010831,0.638489,0.195006,0.057860,0.009325,0.098929,0.061988,0.016352,0.011592,0.009237,0.067379,0.069889,0.003205,0.166659,0.043957,0.215042,0.018193,0.079329,0.009103,0.039361,0.030072,0.750197,0.257543,0.021430,0.029917,0.013606,0.071730,0.229185,0.116586,0.032344,0.007413,0.003729,0.041719,0.028020,0.014150,0.023068,0.424080,0.238952,0.216965,0.020822,0.001748,0.005828,0.004884,0.017080,0.007916,0.016669,0.119467,0.012833,0.009157,AT1
TGTTGGAAGCTCGGTA-1-22_16220_B1,1.0,1.0,95.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3776,8.236685,6059.0,8.709465,15.118006,19.590692,25.383727,37.629972,192.0,5.262690,3.168840,0.0,0.0,0.0,0.0,0.0,0.0,6059.0,3776,0,0.027733,0.414859,0.910561,0.122145,0.005666,0.042518,0.030576,0.015203,0.121399,0.098804,0.119536,0.024286,0.339794,0.091603,0.030221,0.278749,0.002894,0.241318,0.086295,0.001514,0.168115,0.014023,0.136537,0.006779,0.053962,0.006871,0.005770,0.006127,0.046612,0.231813,0.160615,0.016836,0.003369,0.005285,0.001335,0.043407,1.020134,0.102844,0.002140,0.007015,0.110815,0.026650,0.098955,0.383614,0.056468,0.404067,0.012163,0.000212,0.017786,0.003175,0.000582,0.104944,0.014785,0.132177,0.025317,0.009947,Monocyte-derived Mph
TGTTGGATGGACTTCT-1-22_16220_B1,1.0,13.0,53.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,2730,7.912423,4281.0,8.362176,19.504789,24.550339,31.558047,45.877132,284.0,5.652489,6.633964,0.0,0.0,0.0,0.0,0.0,0.0,4281.0,2730,1,0.072429,0.449036,2.438682,0.205547,0.017653,0.100401,0.037879,0.007400,0.128469,0.225288,0.050948,0.029965,0.082476,0.062304,0.020797,0.060529,0.005550,0.010314,0.036070,0.002774,0.178297,0.031913,0.181172,0.010522,0.009545,0.009999,0.009432,0.297448,0.014984,0.029476,0.042504,0.012411,0.017603,0.016918,0.014518,0.023244,0.161680,0.016316,0.013447,0.033981,0.072806,0.007954,0.021004,0.095104,0.053645,0.149471,0.096028,0.000275,0.040803,0.004464,0.001540,0.007772,0.032349,0.043325,0.016523,0.023343,AT2
TGTTGGCCAGACCTAC-1-22_16220_B1,1.0,49.0,47.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,4159,8.333270,7474.0,8.919319,15.948622,20.858978,27.588975,40.500401,300.0,5.707110,4.013915,0.0,0.0,0.0,0.0,0.0,0.0,7474.0,4159,1,0.794082,4.580537,0.870212,0.011166,0.003483,0.021490,0.007070,0.013400,0.337577,0.060844,0.055511,0.041338,0.130497,0.097034,0.022325,0.011413,0.001810,0.007699,0.045953,0.000505,0.302588,0.027830,0.324499,0.007028,0.010651,0.008317,0.005822,0.005205,0.085227,0.051932,0.031908,0.119128,0.018161,0.040580,0.001739,0.021628,0.025011,0.086345,0.001106,0.260140,0.065881,0.006617,0.038130,0.321881,0.190020,0.011823,0.009485,0.006947,0.004004,0.076724,0.088864,0.004982,0.012438,0.107862,0.007276,0.003487,AT1

In [ ]:
adata_vis.obs[adata_vis.uns['mod_0']['factor_names']] = adata_vis.obsm['q05_cell_abundance_w_sf']
adata_vis.obs[adata_vis.uns['mod_1']['factor_names']] = adata_vis.obsm['q05_cell_abundance_w_sf']

In [10]:
adata_vis.uns

{'mod_0': {'date': '2025-07-12',
  'factor_filter': array([], dtype=float64),
  'factor_names': array(['AT0', 'AT1', 'AT2', 'AT2 proliferating',
         'Adventitial fibroblasts', 'Alveolar Mph CCL3+',
         'Alveolar Mph MT-positive', 'Alveolar Mph proliferating',
         'Alveolar fibroblasts', 'Alveolar macrophages', 'B cells',
         'Basal resting', 'CD4 T cells', 'CD8 T cells',
         'Classical monocytes', 'Club (nasal)', 'Club (non-nasal)', 'DC1',
         'DC2', 'Deuterosomal', 'EC aerocyte capillary', 'EC arterial',
         'EC general capillary', 'EC venous pulmonary',
         'EC venous systemic', 'Goblet (bronchial)', 'Goblet (nasal)',
         'Goblet (subsegmental)', 'Hillock-like',
         'Interstitial Mph perivascular', 'Ionocyte',
         'Lymphatic EC differentiating', 'Lymphatic EC mature',
         'Mast cells', 'Mesothelium', 'Migratory DCs',
         'Monocyte-derived Mph', 'Multiciliated (nasal)',
         'Multiciliated (non-nasal)', 'Myofibroblasts', 'NK cells',
         'Neuroendocrine', 'Non-classical monocytes',
         'Peribronchial fibroblasts', 'Pericytes', 'Plasma cells',
         'Plasmacytoid DCs', 'SM activated stress response', 'SMG duct',
         'Smooth muscle', 'Smooth muscle FAM83D+', 'Subpleural fibroblasts',
         'Suprabasal', 'T cells proliferating', 'Unknown',
         'pre-TB secretory'], dtype=object),
  'model_name': 'Cell2locationBaseModule',
  'obs_names': array(['AACACGTGCATCGCAC-1-18_57617_A1', 'AACACTTGGCAAGGAA-1-18_57617_A1',
         'AACAGGATTCATAGTT-1-18_57617_A1', ...,
         'TGTTCAGAACGGTGTA-1-22_16220_B1', 'TGTTCATAGTATGACG-1-22_16220_B1',
         'TGTTGGAAGCTCGGTA-1-22_16220_B1'], shape=(80728,), dtype=object),
  'post_sample_means': {'alpha_g_inverse': array([[0.04507333, 0.28297067, 0.28847557, ..., 0.14932892, 0.43353912,
           0.44960472],
          [0.18472093, 0.24655999, 0.73422974, ..., 0.24826434, 0.13969713,
           0.30641475],
          [0.40665415, 0.4581732 , 0.25938338, ..., 0.19346291, 0.3229563 ,
           0.32001877],
          ...,
          [0.13844189, 0.3588881 , 0.3839808 , ..., 0.15526947, 0.16183357,
           0.08429455],
          [0.30672967, 0.21107124, 0.1795451 , ..., 0.31986207, 0.26388046,
           0.30666137],
          [0.22026892, 0.23215654, 0.14013867, ..., 0.45806283, 0.24040796,
           0.08217736]], shape=(44, 8998), dtype=float32),
   'alpha_g_phi_hyp': array([[2.5997617]], dtype=float32),
   'b_s_groups_per_location': array([[18.983704],
          [19.683426],
          [18.802692],
          ...,
          [19.469784],
          [18.948019],
          [19.465485]], shape=(80728, 1), dtype=float32),
   'detection_hyp_prior_alpha': array([[20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.]], dtype=float32),
   'detection_mean_y_e': array([[0.07396796],
          [0.03815737],
          [0.02513495],
          [0.03264724],
          [0.17574564],
          [0.06403878],
          [0.02252238],
          [0.06759521],
          [0.17470399],
          [0.08891346],
          [0.12585644],
          [0.10432018],
          [0.07684551],
          [0.0774587 ],
          [0.14864758],
          [0.11050208],
          [0.17691295],
          [0.10497786],
          [0.16067493],
          [0.12384127],
          [0.26453114],
          [0.05022947],
          [0.038547  ],
          [0.19861035],
          [0.2299914 ],
          [0.05564449],
          [0.03050013],
          [0.08353373],
          [0.25340423],
          [0.1243073 ],
          [0.42903763],
          [0.24900791],
          [0.19578823],
          [0.20154136],
          [0.04956318],
          [0.06864544],
          [0.09450127],
          [0.18863742],
          [0.27027962],
          [0.28048646],
          [0.04881281],
          [0.13642684],
          [0.04992092],
          [0.14335015]], dtype=float32),
   'detection_y_s': array([[0.24184209],
          [0.12603994],
          [0.10808852],
          ...,
          [0.10628416],
          [0.41207966],
          [0.18645336]], shape=(80728, 1), dtype=float32),
   'k_r_factors_per_groups': array([[ 1.485336 ],
          [25.009512 ],
          [25.987707 ],
          [ 3.1861908],
          [25.679846 ],
          [25.614836 ],
          [24.972729 ],
          [15.621013 ],
          [25.59797  ],
          [25.5932   ],
          [ 5.379641 ],
          [26.00846  ],
          [25.765636 ],
          [24.648724 ],
          [25.3819   ],
          [25.458714 ],
          [24.925852 ],
          [25.730154 ],
          [25.895563 ],
          [25.623295 ],
          [25.028162 ],
          [25.28126  ],
          [25.673227 ],
          [25.959578 ],
          [25.718393 ],
          [25.513393 ],
          [26.453394 ],
          [25.839169 ],
          [24.919024 ],
          [25.72619  ],
          [24.623596 ],
          [25.326992 ],
          [24.893173 ],
          [25.543558 ],
          [23.879257 ],
          [26.425623 ],
          [24.51943  ],
          [26.310617 ],
          [25.958261 ],
          [25.609493 ],
          [25.858374 ],
          [24.950459 ],
          [26.050728 ],
          [26.422829 ],
          [25.744152 ],
          [24.84002  ],
          [25.912539 ],
          [12.32154  ],
          [26.187607 ],
          [24.972101 ]], dtype=float32),
   'm_g': array([[2.0360293 , 0.81380147, 2.4147122 , ..., 1.0654323 , 0.99087805,
           1.6241597 ]], shape=(1, 8998), dtype=float32),
   'm_g_alpha_e_inv': array([[0.7951302]], dtype=float32),
   'm_g_mean': array([[0.83919275]], dtype=float32),
   'n_s_cells_per_location': array([[ 9.133275 ],
          [ 8.7781515],
          [ 8.34685  ],
          ...,
          [ 8.567943 ],
          [10.1585   ],
          [10.910565 ]], shape=(80728, 1), dtype=float32),
   's_g_gene_add': array([[0.01107701, 0.01061029, 0.01047583, ..., 0.0111986 , 0.01110194,
           0.01131282],
          [0.0196033 , 0.02007418, 0.01973099, ..., 0.0202132 , 0.02014768,
           0.02038036],
          [0.00783525, 0.00773396, 0.00777083, ..., 0.00780682, 0.00791366,
           0.0080057 ],
          ...,
          [0.00668755, 0.00683682, 0.00661388, ..., 0.00664569, 0.00667867,
           0.00688316],
          [0.0114285 , 0.01170747, 0.01126951, ..., 0.01171684, 0.01156998,
           0.01182481],
          [0.00859488, 0.00857826, 0.00869629, ..., 0.00880038, 0.00853165,
           0.00881686]], shape=(44, 8998), dtype=float32),
   's_g_gene_add_alpha_e_inv': array([[0.25405884],
          [0.23217028],
          [0.20041375],
          [0.2073854 ],
          [0.32376048],
          [0.28668386],
          [0.20863654],
          [0.212075  ],
          [1.6196313 ],
          [0.20607887],
          [1.5170181 ],
          [0.20348307],
          [0.2468412 ],
          [0.21445258],
          [0.20381358],
          [0.21775831],
          [0.26163462],
          [0.2114036 ],
          [0.210379  ],
          [0.30276594],
          [1.6922865 ],
          [0.21002187],
          [0.21670386],
          [0.23110455],
          [0.30478382],
          [0.2098293 ],
          [0.2430046 ],
          [1.5578936 ],
          [1.8017083 ],
          [0.24038352],
          [1.6515001 ],
          [1.6936057 ],
          [1.4633658 ],
          [1.0314361 ],
          [0.23170322],
          [1.2974434 ],
          [0.21069908],
          [0.33704206],
          [1.6485671 ],
          [1.7675418 ],
          [0.22420292],
          [0.20610453],
          [0.23386775],
          [0.25440696]], dtype=float32),
   's_g_gene_add_alpha_hyp': array([[1.8332958]], dtype=float32),
   's_g_gene_add_mean': array([[0.01123998],
          [0.02011453],
          [0.00788099],
          [0.00709129],
          [0.01151234],
          [0.0177361 ],
          [0.00989847],
          [0.00937263],
          [0.18553796],
          [0.00716939],
          [0.30970868],
          [0.00479101],
          [0.0148847 ],
          [0.00986595],
          [0.00587246],
          [0.01072974],
          [0.01084732],
          [0.00450257],
          [0.01065511],
          [0.01689575],
          [0.23299327],
          [0.00364867],
          [0.0104972 ],
          [0.00916377],
          [0.00848865],
          [0.01026923],
          [0.02116233],
          [0.34103194],
          [0.79387766],
          [0.01333209],
          [0.25462762],
          [0.351451  ],
          [0.5076779 ],
          [0.04965124],
          [0.01387339],
          [0.38869745],
          [0.00954419],
          [0.00924821],
          [0.13630596],
          [0.14317794],
          [0.01118452],
          [0.00675244],
          [0.01159478],
          [0.00869712]], dtype=float32),
   'u_sf_mRNA_factors': array([[  43.27225  ,    9.056902 ,    6.6345277, ...,  328.86285  ,
             50.870056 ,   25.603977 ],
          [ 660.36633  , 1774.0796   , 1228.0209   , ...,  561.4212   ,
            186.0535   , 1316.3715   ],
          [  96.33351  ,  278.5285   ,  348.4859   , ...,  245.15443  ,
             85.80901  ,   42.140175 ],
          ...,
          [ 856.051    ,  742.2143   , 3369.9353   , ...,   89.58368  ,
             96.523315 ,  481.07397  ],
          [  35.8963   ,   37.343098 ,   86.390274 , ..., 1287.2733   ,
             37.970192 ,   23.380404 ],
          [ 219.0056   ,  965.75024  , 2604.1594   , ...,  694.48956  ,
            236.64474  ,  140.51656  ]], shape=(80728, 56), dtype=float32),
   'w_sf': array([[0.02203752, 0.00546712, 0.00285226, ..., 0.10664367, 0.0257767 ,
           0.01208481],
          [0.33630502, 1.0709155 , 0.5279835 , ..., 0.18205832, 0.09427729,
           0.6213217 ],
          [0.04905967, 0.16813257, 0.14983013, ..., 0.07949856, 0.04348136,
           0.01989056],
          ...,
          [0.43595928, 0.4480348 , 1.4488655 , ..., 0.02905044, 0.04891014,
           0.22706044],
          [0.01828089, 0.02254216, 0.03714262, ..., 0.41744024, 0.01924027,
           0.01103478],
          [0.1115322 , 0.5829704 , 1.1196288 , ..., 0.22521082, 0.11991241,
           0.06632234]], shape=(80728, 56), dtype=float32),
   'x_fr_group2fact': array([[7.4574077e-01, 4.4707041e+00, 5.6109686e+00, ..., 3.1498754e-01,
           3.0417308e-01, 1.1079271e-01],
          [5.3670751e-03, 1.6435852e-03, 6.9940242e-04, ..., 1.2048734e-02,
           5.5867308e-03, 4.8436606e-03],
          [5.6856168e-03, 3.7769242e-03, 4.2247958e-03, ..., 1.0237762e-02,
           5.5119628e-03, 5.7547791e-03],
          ...,
          [2.8347194e-01, 9.8762110e-02, 7.3515236e-02, ..., 2.1846967e-02,
           1.4287218e-02, 3.9062586e-01],
          [5.6083305e-03, 3.8730358e-03, 4.0966421e-03, ..., 1.0775576e-02,
           5.4494399e-03, 5.5757002e-03],
          [6.1117215e-03, 3.9155423e-03, 4.2954329e-03, ..., 8.8118250e-03,
           5.4708417e-03, 6.3917227e-03]], shape=(50, 56), dtype=float32),
   'z_sr_groups_factors': array([[0.00297431, 0.25777087, 0.22607265, ..., 0.04426467, 0.20072255,
           0.18629064],
          [0.23852716, 0.1609975 , 0.13586149, ..., 0.14872724, 0.18979932,
           0.20641258],
          [0.11278886, 0.1638884 , 0.1493839 , ..., 0.04243067, 0.14991911,
           0.17526652],
          ...,
          [0.1279265 , 0.20985968, 0.18215539, ..., 0.23063985, 0.15403274,
           0.16810994],
          [0.00698912, 0.27297124, 0.23925517, ..., 0.04143559, 0.20091659,
           0.17457974],
          [0.14563358, 0.27821627, 0.21310815, ..., 0.13550451, 0.23981813,
           0.2534359 ]], shape=(80728, 50), dtype=float32)},
  'post_sample_q05': {'alpha_g_inverse': array([[0.02056184, 0.06635685, 0.10803496, ..., 0.032645  , 0.22343184,
           0.29866397],
          [0.16729847, 0.0571336 , 0.4385411 , ..., 0.05052501, 0.02785712,
           0.10946082],
          [0.3846365 , 0.15832454, 0.0691763 , ..., 0.03588474, 0.09430987,
           0.09546956],
          ...,
          [0.12693742, 0.24278156, 0.25343835, ..., 0.04263641, 0.05148577,
           0.02012312],
          [0.2891868 , 0.0570765 , 0.05280697, ..., 0.09964149, 0.08734471,
           0.14717594],
          [0.21030451, 0.08117054, 0.04794898, ..., 0.28772572, 0.09834237,
           0.02264166]], shape=(44, 8998), dtype=float32),
   'alpha_g_phi_hyp': array([[2.5929346]], dtype=float32),
   'b_s_groups_per_location': array([[14.832001],
          [15.350249],
          [14.78304 ],
          ...,
          [15.18845 ],
          [14.723797],
          [14.95316 ]], shape=(80728, 1), dtype=float32),
   'detection_hyp_prior_alpha': array([[20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.],
          [20.]], dtype=float32),
   'detection_mean_y_e': array([[0.07337439],
          [0.03776436],
          [0.0249066 ],
          [0.03241587],
          [0.17397748],
          [0.06351545],
          [0.02233034],
          [0.06700458],
          [0.17334041],
          [0.08818326],
          [0.12470859],
          [0.10350092],
          [0.07625232],
          [0.07684043],
          [0.14725968],
          [0.109617  ],
          [0.17538588],
          [0.10417593],
          [0.15857507],
          [0.12280767],
          [0.2623033 ],
          [0.0498528 ],
          [0.03822024],
          [0.1967702 ],
          [0.22807054],
          [0.05517624],
          [0.03022746],
          [0.08293076],
          [0.25135523],
          [0.12336159],
          [0.42373738],
          [0.24677202],
          [0.19410674],
          [0.19960833],
          [0.04918636],
          [0.06810009],
          [0.09362587],
          [0.18700308],
          [0.26771155],
          [0.2780927 ],
          [0.04837805],
          [0.13522747],
          [0.04953992],
          [0.14221041]], dtype=float32),
   'detection_y_s': array([[0.23567687],
          [0.12240638],
          [0.10386625],
          ...,
          [0.10207163],
          [0.40450788],
          [0.18160209]], shape=(80728, 1), dtype=float32),
   'k_r_factors_per_groups': array([[ 1.1868162],
          [19.276855 ],
          [19.657814 ],
          [ 2.5243232],
          [19.815214 ],
          [19.519535 ],
          [19.492182 ],
          [12.18456  ],
          [19.615116 ],
          [19.603045 ],
          [ 4.2683125],
          [19.716375 ],
          [20.131533 ],
          [19.137424 ],
          [19.754139 ],
          [19.686981 ],
          [19.017082 ],
          [20.031813 ],
          [20.181421 ],
          [19.614845 ],
          [19.736074 ],
          [19.203808 ],
          [19.862223 ],
          [19.89421  ],
          [19.49438  ],
          [19.772316 ],
          [19.935362 ],
          [19.91876  ],
          [19.195389 ],
          [19.769297 ],
          [19.154198 ],
          [19.182598 ],
          [19.222128 ],
          [19.706081 ],
          [18.6228   ],
          [19.980165 ],
          [19.000143 ],
          [20.27952  ],
          [20.398405 ],
          [19.612766 ],
          [19.702112 ],
          [19.140245 ],
          [19.87033  ],
          [20.479372 ],
          [19.32365  ],
          [19.082216 ],
          [19.949295 ],
          [ 9.580204 ],
          [20.63892  ],
          [19.31894  ]], dtype=float32),
   'm_g': array([[2.0320704, 0.8043919, 2.3931937, ..., 1.0502594, 0.9792827,
           1.608907 ]], shape=(1, 8998), dtype=float32),
   'm_g_alpha_e_inv': array([[0.78576624]], dtype=float32),
   'm_g_mean': array([[0.8275818]], dtype=float32),
   'n_s_cells_per_location': array([[6.622127 ],
          [6.2251062],
          [6.127487 ],
          ...,
          [6.1649084],
          [7.4148145],
          [8.081102 ]], shape=(80728, 1), dtype=float32),
   's_g_gene_add': array([[0.00706901, 0.00700015, 0.00686757, ..., 0.00722598, 0.00690784,
           0.00711346],
          [0.01328029, 0.01280245, 0.01326751, ..., 0.01292608, 0.01362026,
           0.01327565],
          [0.00543676, 0.00532266, 0.00562691, ..., 0.00548143, 0.00564418,
           0.00566   ],
          ...,
          [0.00461998, 0.00486463, 0.00466427, ..., 0.0045814 , 0.00462379,
           0.0048409 ],
          [0.00765048, 0.00774301, 0.00757724, ..., 0.00742759, 0.00753649,
           0.00781047],
          [0.00558746, 0.00540419, 0.00562748, ..., 0.00570784, 0.00539111,
           0.00555822]], shape=(44, 8998), dtype=float32),
   's_g_gene_add_alpha_e_inv': array([[0.25080764],
          [0.22944708],
          [0.19806641],
          [0.2048408 ],
          [0.32002687],
          [0.2834695 ],
          [0.20626073],
          [0.20954292],
          [1.6032522 ],
          [0.20374969],
          [1.5020835 ],
          [0.20117472],
          [0.24385184],
          [0.2119328 ],
          [0.20132749],
          [0.21528453],
          [0.258796  ],
          [0.20896101],
          [0.20774946],
          [0.29898095],
          [1.6774364 ],
          [0.20746632],
          [0.21422884],
          [0.22841333],
          [0.30117416],
          [0.20743868],
          [0.24007475],
          [1.5427079 ],
          [1.7849253 ],
          [0.23734945],
          [1.6347215 ],
          [1.6774132 ],
          [1.4475234 ],
          [1.0203056 ],
          [0.22901066],
          [1.2834175 ],
          [0.20810603],
          [0.33287638],
          [1.6327252 ],
          [1.7491118 ],
          [0.2214987 ],
          [0.2036295 ],
          [0.23097043],
          [0.25137076]], dtype=float32),
   's_g_gene_add_alpha_hyp': array([[1.4466071]], dtype=float32),
   's_g_gene_add_mean': array([[0.01118712],
          [0.02002897],
          [0.0078532 ],
          [0.00706414],
          [0.01144998],
          [0.01764952],
          [0.00985837],
          [0.00933797],
          [0.18093164],
          [0.00714334],
          [0.30163607],
          [0.00477502],
          [0.01482159],
          [0.00983098],
          [0.00585277],
          [0.01068784],
          [0.01079561],
          [0.00448543],
          [0.01061784],
          [0.01680917],
          [0.226199  ],
          [0.00363573],
          [0.0104547 ],
          [0.00912935],
          [0.00844021],
          [0.01023009],
          [0.02107413],
          [0.33197492],
          [0.7716953 ],
          [0.01327555],
          [0.2470729 ],
          [0.34127593],
          [0.49539143],
          [0.04907558],
          [0.01381706],
          [0.37959996],
          [0.00951003],
          [0.00919654],
          [0.13234086],
          [0.13932705],
          [0.01113614],
          [0.00672955],
          [0.01155033],
          [0.00866119]], dtype=float32),

In [11]:
adata_vis.obsm["q05_cell_abundance_w_sf"]

array([[9.66656720e-04, 8.13243969e-05, 2.29026300e-05, ...,
        4.45834920e-02, 1.35436561e-03, 3.23585438e-04],
       [1.37827709e-01, 8.02714944e-01, 3.41799647e-01, ...,
        8.98878872e-02, 1.20390868e-02, 3.79554302e-01],
       [5.16986102e-03, 5.98323643e-02, 8.23287666e-02, ...,
        2.13461649e-02, 2.78973859e-03, 4.72171174e-04],
       ...,
       [2.77333297e-02, 4.14859265e-01, 9.10561383e-01, ...,
        1.32177249e-01, 2.53166985e-02, 9.94704384e-03],
       [7.24286661e-02, 4.49035585e-01, 2.43868160e+00, ...,
        4.33246233e-02, 1.65227652e-02, 2.33426578e-02],
       [7.94081926e-01, 4.58053684e+00, 8.70211720e-01, ...,
        1.07862167e-01, 7.27577042e-03, 3.48671083e-03]],
      shape=(160702, 56))

In [12]:
adata_vis.uns['mod'] = adata_vis.uns['mod_0']

In [13]:
from cell2location import run_colocation
res_dict, adata_vis = run_colocation(
    adata_vis,
    model_name='CoLocatedGroupsSklearnNMF',
    train_args={
      'n_fact': np.arange(12,13), # IMPORTANT: use a wider range of the number of factors (5-30)
      'sample_name_col': 'library_id', # columns in adata_vis.obs that identifies sample,
      'cell_abundance_obsm': 'means_cell_abundance_w_sf',

      'n_restarts': 3 # number of training restarts
    },
    # the hyperparameters of NMF can be also adjusted:
    model_kwargs={'alpha': 0.01, 'init': 'random', "nmf_kwd_args": {"tol": 0.000001}},
    export_args={'path': '/Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/'}
)

### Analysis name: CoLocatedGroupsSklearnNMF_12combinations_160702locations_56factors

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/sklearn/utils/extmath.py:205: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s18_57617_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_33940_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_24241_A2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s19_35057_C3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_17688_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_28197_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_22642_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_41501_C1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_33362_C4_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_41847_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_41615_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_06301_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_05738_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_57231_A3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_25528_A3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s22_18446_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s22_18440_A2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s23_15209_A3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s22_50637_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s23_50343_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s23_41922_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s24_10794_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_12743_C1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_55244_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s23_45450_A3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s24_23755_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s16_53837_A10_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s19_48719_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s17_35291_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s16_46257_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s18_23779_A2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s12_39986_A2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s20_26330_B3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_24837_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s06_30914_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s19_18542_A4_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s24_27523_C5_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s11_13888_A1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s17_25789_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s08_38774_B2_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s16_39724_B1_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_24095_A3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s21_55747_C3_p99.2.pdf

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/cell2location/run_colocation.py:384: FutureWarning: Use `squidpy.pl.spatial_scatter` instead.
  sc.pl.spatial(

WARNING: saving figure to file /Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/cell2location/CoLocatedComb_r12/CoLocatedGroupsSklearnNMF_160702locations_56factors/spatial/showcell_density_mean_n_fact12_s22_16220_B1_p99.2.pdf

In [14]:
adata_vis.write(os.path.join(h5ad_dir,"adata_vis_assigned_cell_types_nfact12.h5ad"))