In [1]:
import scanpy as sc  
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl 
#import cell2location 
import pandas as pd
#import torch 
import os

pd.set_option('display.max_columns',500)
pd.set_option('display.max_categories',60)
pd.set_option('display.max_rows', 500)
# Set general parameters for publication-ready figures
plt.rcParams.update({
    'pdf.fonttype': 42,
    'font.family': 'Arial',  # Set font to Arial
    'font.size': 14,  # Set font size to at least 14
    'axes.labelsize': 14,  # Axes labels size
    'axes.titlesize': 16,  # Title size for axes
    'xtick.labelsize': 14,  # X-tick label size
    'ytick.labelsize': 14,  # Y-tick label size
    'legend.fontsize': 14,  # Legend font size
    'figure.titlesize': 16,  # Figure title size
    'lines.linewidth': 2,  # Line width for clarity
    'axes.linewidth': 1.5,  # Axis line width
    'xtick.major.width': 1.5,
    'ytick.major.width': 1.5,
    'text.color': 'black',  # Make sure text is black (not grey)
    'axes.labelcolor': 'black',  # Ensure axes labels are black
    'axes.edgecolor': 'black',  # Ensure edge of axes is black
    'axes.facecolor': 'white',
    'xtick.color': 'black',  # Ensure X-tick marks are black
    'ytick.color': 'black',  # Ensure Y-tick marks are black
    'axes.titlepad': 20  # Padding for title
})

/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/Users/jk/miniconda3/envs/scvi-tools/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)

In [2]:
adata_vis = sc.read_h5ad("/Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/nfact12/h5ad/adata_vis_assigned_cell_types_nfact12_assigned_factors_log_minmax.h5ad")

In [3]:
adata_vis.var

                gene_ids
SAMD11   ENSG00000187634
NOC2L    ENSG00000188976
KLHL17   ENSG00000187961
PLEKHN1  ENSG00000187583
PERM1    ENSG00000187642
...                  ...
MT-ND4L  ENSG00000212907
MT-ND4   ENSG00000198886
MT-ND5   ENSG00000198786
MT-ND6   ENSG00000198695
MT-CYB   ENSG00000198727

[16959 rows x 1 columns]

In [4]:
adata_vis.obs

,in_tissue,array_row,array_col,library_id,alignment,desired_rc,actual_rc,xmin,xmax,ymin,ymax,hpx,vpx,slide,area,date,cytassist_ver,seq_batch,probe_date,probe_lot,probe_group,cond,cond_rep,rep,age,sex,bmi,packyears,FVC,DLCO,6MWD,outcome_long,tte_long,outcome_24m,tte_24m,lobe_lr,lobe,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,total_counts_ribo,log1p_total_counts_ribo,pct_counts_ribo,total_counts_hb,log1p_total_counts_hb,pct_counts_hb,n_counts,n_genes,training_batch,AT0,AT1,AT2,AT2 proliferating,Adventitial fibroblasts,Alveolar Mph CCL3+,Alveolar Mph MT-positive,Alveolar Mph proliferating,Alveolar fibroblasts,Alveolar macrophages,B cells,Basal resting,CD4 T cells,CD8 T cells,Classical monocytes,Club (nasal),Club (non-nasal),DC1,DC2,Deuterosomal,EC aerocyte capillary,EC arterial,EC general capillary,EC venous pulmonary,EC venous systemic,Goblet (bronchial),Goblet (nasal),Goblet (subsegmental),Hillock-like,Interstitial Mph perivascular,Ionocyte,Lymphatic EC differentiating,Lymphatic EC mature,Mast cells,Mesothelium,Migratory DCs,Monocyte-derived Mph,Multiciliated (nasal),Multiciliated (non-nasal),Myofibroblasts,NK cells,Neuroendocrine,Non-classical monocytes,Peribronchial fibroblasts,Pericytes,Plasma cells,Plasmacytoid DCs,SM activated stress response,SMG duct,Smooth muscle,Smooth muscle FAM83D+,Subpleural fibroblasts,Suprabasal,T cells proliferating,Unknown,pre-TB secretory,cell_type_assigned,mean_nUMI_factorsfact_0,mean_nUMI_factorsfact_1,mean_nUMI_factorsfact_2,mean_nUMI_factorsfact_3,mean_nUMI_factorsfact_4,mean_nUMI_factorsfact_5,mean_nUMI_factorsfact_6,mean_nUMI_factorsfact_7,mean_nUMI_factorsfact_8,mean_nUMI_factorsfact_9,mean_nUMI_factorsfact_10,mean_nUMI_factorsfact_11,ATI/Endo,Perib. FB,Airway,B,Alv. macro,Alv. FB/immune,Adv. FB,Macro,Immune,SMC,ATII,Plasma,ATI/Endo_log_minmax,Perib. FB_log_minmax,Airway_log_minmax,B_log_minmax,Alv. macro_log_minmax,Alv. FB/immune_log_minmax,Adv. FB_log_minmax,Macro_log_minmax,Immune_log_minmax,SMC_log_minmax,ATII_log_minmax,Plasma_log_minmax,factor_assigned
AACACGTGCATCGCAC-1-18_57617_A1,1.0,76.0,22.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3961,8.284504,7804.0,8.962520,31.765761,35.212711,39.928242,49.410559,629.0,6.445720,8.059970,0.0,0.0,0.0,0.0,0.0,0.0,7804.0,3961,0,0.000967,0.000081,0.000023,0.000279,0.234594,0.009023,0.003434,0.045472,0.387183,0.001108,3.730742,0.001663,0.065855,0.019768,0.004821,0.127872,0.000417,0.008481,0.040385,0.010641,0.001719,0.002331,0.000529,0.001759,0.004936,0.001933,0.000464,0.042375,0.002770,0.058909,0.003027,0.003101,0.008538,0.003847,0.000322,0.044897,0.017594,0.026567,0.000907,0.003966,0.016523,0.092378,0.008129,0.037726,0.014092,0.968134,0.362111,0.025284,0.008943,0.038652,0.060598,0.231837,0.004889,0.044583,0.001354,0.000324,B cells,0.000000,0.000000,0.000000,3.568719,0.000000,2.327530,0.081827,0.000000,0.780313,0.000000,0.000000,1.475469,0.000000,0.000000,0.000000,3.568719,0.000000,2.327530,0.081827,0.000000,0.780313,0.000000,0.000000,1.475469,0.000000,0.000000,0.000000,0.773084,0.000000,0.717544,0.502845,0.000000,0.620036,0.000000,0.000000,0.740151,B
AACACTTGGCAAGGAA-1-18_57617_A1,1.0,47.0,71.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3322,8.108623,5412.0,8.596559,15.909091,20.842572,27.475979,40.742794,280.0,5.638355,5.173688,0.0,0.0,0.0,0.0,0.0,0.0,5412.0,3322,0,0.137828,0.802715,0.341800,0.009572,0.139944,0.039461,0.032829,0.186727,0.888112,0.481472,0.039227,0.013804,0.056936,0.042788,0.031012,0.009081,0.043570,0.023910,0.040213,0.001578,1.365678,0.136504,0.618607,0.156473,0.098999,0.008318,0.010266,0.010062,0.009213,0.056085,0.024774,0.080588,0.040189,0.030853,0.005049,0.038562,0.017642,0.068411,0.598156,0.124178,0.036192,0.026985,0.061592,0.055564,0.479931,0.034395,0.011473,0.129968,0.007446,0.244876,0.049037,0.007688,0.022190,0.089888,0.012039,0.379554,EC aerocyte capillary,9.937147,0.000000,1.645782,0.000000,0.261246,3.300004,0.000000,0.000000,0.000000,0.410853,0.000000,0.000000,9.937147,0.000000,1.645782,0.000000,0.261246,3.300004,0.000000,0.000000,0.000000,0.410853,0.000000,0.000000,0.837606,0.000000,0.718571,0.000000,0.569461,0.749843,0.000000,0.000000,0.000000,0.590861,0.000000,0.000000,ATI/Endo
AACAGGATTCATAGTT-1-18_57617_A1,1.0,49.0,43.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2120,7.659643,3313.0,8.105911,26.048898,30.878358,37.488681,51.101720,538.0,6.289716,16.239059,0.0,0.0,0.0,0.0,0.0,0.0,3313.0,2120,0,0.005170,0.059832,0.082329,0.001831,0.001260,0.013375,0.011541,0.018772,0.068402,0.020841,0.011103,0.004326,0.079482,0.039857,0.005894,0.012759,0.000413,0.376290,0.007926,0.002451,1.006702,0.058915,2.460315,0.390035,0.384114,0.002900,0.001124,0.012576,0.005301,0.008660,0.003291,0.010103,0.009291,0.070889,0.000651,0.026347,0.006695,0.001637,0.001180,0.004225,0.024105,0.055135,0.015300,0.071425,0.144042,0.012755,0.018465,0.034665,0.005432,0.011212,0.009665,0.028604,0.002229,0.021346,0.002790,0.000472,EC general capillary,9.307676,0.000000,0.000000,0.000000,0.000000,0.236044,0.000000,0.000000,0.000000,0.005353,0.000000,0.000000,9.307676,0.000000,0.000000,0.000000,0.000000,0.236044,0.000000,0.000000,0.000000,0.005353,0.000000,0.000000,0.831651,0.000000,0.000000,0.000000,0.000000,0.506089,0.000000,0.000000,0.000000,0.181447,0.000000,0.000000,ATI/Endo
AACAGGTTCACCGAAG-1-18_57617_A1,1.0,51.0,41.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,2388,7.778630,3665.0,8.206857,25.702592,29.795362,35.470668,48.485675,697.0,6.548219,19.017735,0.0,0.0,0.0,0.0,0.0,0.0,3665.0,2388,1,0.001563,0.020343,0.057659,0.001120,0.005092,0.002046,0.005805,0.000767,0.061047,0.002963,0.117381,0.004090,0.077575,0.054498,0.028830,0.167655,0.000468,0.001589,0.012085,0.020475,0.162310,0.051763,2.538344,0.109793,0.134852,0.001277,0.000667,0.001587,0.007030,0.016640,0.003956,0.062362,0.013975,0.012171,0.001957,0.069829,0.010399,0.113839,0.003326,0.003756,0.046806,0.004957,0.011046,0.015874,0.085721,0.021336,0.006211,0.002165,0.172565,0.029759,0.001750,0.015225,0.002373,0.085016,0.002622,0.000468,EC general capillary,6.992801,0.000000,0.000000,0.080432,0.000000,0.000000,0.000000,0.000000,0.680440,0.012156,0.000000,0.000000,6.992801,0.000000,0.000000,0.080432,0.000000,0.000000,0.000000,0.000000,0.680440,0.012156,0.000000,0.000000,0.805631,0.000000,0.000000,0.415806,0.000000,0.000000,0.000000,0.000000,0.607305,0.252892,0.000000,0.000000,ATI/Endo
AACAGTCAGGCTCCGC-1-18_57617_A1,1.0,24.0,6.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,4939,8.505121,10317.0,9.241645,17.514781,22.545314,28.777745,40.544732,498.0,6.212606,4.826984,0.0,0.0,0.0,0.0,0.0,0.0,10317.0,4939,1,0.571262,0.794535,0.611508,0.019281,0.012665,0.101478,0.013556,0.016001,0.026405,0.450508,0.019763,0.977336,0.043126,0.032375,0.010553,0.033321,0.003311,0.055528,0.082817,0.013789,0.064305,0.007815,0.053782,0.002625,0.002509,0.011348,0.336812,0.006089,0.754471,0.345387,0.042870,0.015813,0.003935,0.003842,0.003417,0.006994,1.927120,0.014479,0.006172,0.104371,0.041883,0.010310,0.027616,0.826019,0.035608,0.000658,0.007651,0.000577,0.005258,0.064397,0.001486,0.004463,0.031568,0.004771,0.007579,0.018862,Monocyte-derived Mph,4.826100,0.950258,0.684971,0.000000,0.357449,0.000000,0.000000,2.262426,0.274459,0.098402,0.552775,0.000000,4.826100,0.950258,0.684971,0.000000,0.357449,0.000000,0.000000,2.262426,0.274459,0.098402,0.552775,0.000000,0.771889,0.735721,0.633608,0.000000,0.601415,0.000000,0.000000,0.788568,0.522992,0.451357,0.645817,0.000000,Macro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGTTCATTGGTCCAAG-1-22_16220_B1,1.0,55.0,99.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,7129,8.872067,19251.0,9.865370,16.149810,20.637889,26.414212,37.296764,781.0,6.661855,4.056932,0.0,0.0,0.0,0.0,0.0,0.0,19251.0,7129,1,0.367223,2.524808,4.255534,0.157300,0.003124,0.119464,0.055409,0.065133,1.719185,0.480502,0.182870,0.047675,0.994454,0.724625,0.103567,0.079388,0.028916,0.097227,0.212938,0.001171,3.753310,0.227036,2.941121,0.053537,0.037008,0.047620,0.069989,0.071654,0.015006,0.810489,0.170295,0.329601,0.037099,0.113724,0.007770,0.183838,0.055765,0.102231,0.001477,0.592959,0.413240,0.058103,0.221728,0.352980,1.715962,0.041914,0.081070,0.004009,0.007826,0.010457,0.007975,0.049609,0.025066,0.487826,0.039088,0.013980,AT2,28.651281,0.019151,0.000000,0.000000,0.000000,3.422668,0.000000,0.000000,2.698218,0.000000,2.838355,0.000000,28.651281,0.019151,0.000000,0.000000,0.000000,3.422668,0.000000,0.000000,2.698218,0.000000,2.838355,0.000000,0.933965,0.322197,0.000000,0.000000,0.000000,0.753220,0.000000,0.000000,0.735437,0.000000,0.812934,0.000000,ATI/Endo
TGTTGCGTCCAAGATT-1-22_16220_B1,1.0,51.0,65.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3768,8.234565,7184.0,8.879751,19.724388,24.972160,31.556236,44.863586,362.0,5.894403,5.038976,0.0,0.0,0.0,0.0,0.0,0.0,7184.0,3768,1,0.042970,3.252706,0.800204,0.078585,0.015209,0.153775,0.020274,0.010831,0.638489,0.195006,0.057860,0.009325,0.098929,0.061988,0.016352,0.011592,0.009237,0.067379,0.069889,0.003205,0.166659,0.043957,0.215042,0.018193,0.079329,0.009103,0.039361,0.030072,0.750197,0.257543,0.021430,0.029917,0.013606,0.071730,0.229185,0.116586,0.032344,0.007413,0.003729,0.041719,0.028020,0.014150,0.023068,0.424080,0.238952,0.216965,0.020822,0.001748,0.005828,0.004884,0.017080,0.007916,0.016669,0.119467,0.012833,0.009157,AT1,13.340566,0.466495,0.000000,0.000000,0.000000,0.186981,0.000000,0.000000,0.000000,0.000000,0.000000,0.386425,13.340566,0.466495,0.000000,0.000000,0.000000,0.186981,0.000000,0.000000,0.000000,0.000000,0.000000,0.386425,0.864406,0.659508,0.000000,0.000000,0.000000,0.484627,0.000000,0.000000,0.000000,0.000000,0.000000,0.604454,ATI/Endo
TGTTGGAAGCTCGGTA-1-22_16220_B1,1.0,1.0,95.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,3776,8.236685,6059.0,8.709465,15.118006,19.590692,25.383727,37.629972,192.0,5.262690,3.168840,0.0,0.0,0.0,0.0,0.0,0.0,6059.0,3776,0,0.027733,0.414859,0.910561,0.122145,0.005666,0.042518,0.030576,0.015203,0.121399,0.098804,0.119536,0.024286,0.339794,0.091603,0.030221,0.278749,0.002894,0.241318,0.086295,0.001514,0.168115,0.014023,0.136537,0.006779,0.053962,0.006871,0.005770,0.006127,0.046612,0.231813,0.160615,0.016836,0.003369,0.005285,0.001335,0.043407,1.020134,0.102844,0.002140,0.007015,0.110815,0.026650,0.098955,0.383614,0.056468,0.404067,0.012163,0.000212,0.017786,0.003175,0.000582,0.104944,0.014785,0.132177,0.025317,0.009947,Monocyte-derived Mph,3.815214,0.326528,0.000000,0.000000,0.000000,0.434772,0.000000,1.147775,2.356703,0.000000,1.008671,0.649322,3.815214,0.326528,0.000000,0.000000,0.000000,0.434772,0.000000,1.147775,2.356703,0.000000,1.008671,0.649322,0.750505,0.621335,0.000000,0.000000,0.000000,0.562441,0.000000,0.719336,0.722845,0.000000,0.707224,0.656987,ATI/Endo
TGTTGGATGGACTTCT-1-22_16220_B1,1.0,13.0,53.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,2730,7.912423,4281.0,8.362176,19.504789,24.550339,31.558047,45.877132,284.0,5.652489,6.633964,0.0,0.0,0.0,0.0,0.0,0.0,4281.0,2730,1,0.072429,0.449036,2.438682,0.205547,0.017653,0.100401,0.037879,0.007400,0.128469,0.225288,0.050948,0.029965,0.082476,0.062304,0.020797,0.060529,0.005550,0.010314,0.036070,0.002774,0.178297,0.031913,0.181172,0.010522,0.009545,0.009999,0.009432,0.297448,0.014984,0.029476,0.042504,0.012411,0.017603,0.016918,0.014518,0.023244,0.161680,0.016316,0.013447,0.033981,0.072806,0.007954,0.021004,0.095104,0.053645,0.149471,0.096028,0.000275,0.040803,0.004464,0.001540,0.007772,0.032349,0.043325,0.016523,0.023343,AT2,4.212741,0.000000,0.019256,0.000000,0.097273,0.316283,0.000000,0.126336,0.884804,0.000000,3.221982,0.317652,4.212741,0.000000,0.019256,0.000000,0.097273,0.316283,0.000000,0.126336,0.884804,0.000000,3.221982,0.317652,0.759522,0.000000,0.291874,0.000000,0.469099,0.533072,0.000000,0.494788,0.631720,0.000000,0.825891,0.584633,ATII
TGTTGGCCAGACCTAC-1-22_16220_B1,1.0,49.0,47.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,4159,8.333270,7474.0,8.919319,15.948622,20.858978,27.588975,40.500401,300.0,5.707110,4.013915,0.0,0.0,0.0,0.0,0.0,0.0,7474.0,4159,1,0.794082,4.580537,0.870212,0.011166,0.003483,0.021490,0.007070,0.013400,0.337577,0.060844,0.055511,0.041338,0.130497,0.097034,0.022325,0.011413,0.001810,0.007699,0.045953,0.000505,0.302588,0.027830,0.324499,0.007028,0.010651,0.008317,0.005822,0.005205,0.085227,0.051932,0.031908,0.119128,0.018161,0.040580,0.001739,0.021628,0.025011,0.086345,0.001106,0.260140,0.065881,0.006617,0.038130,0.321881,0.190020,0.011823,0.009485,0.006947,0.004004,0.076724,0.088864,0.004982,0.012438,0.107862,0.007276,0.003487,AT1,17.042360,0.237097,0.087739,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030620,0.000000,0.000000,17.042360,0.237097,0.087739,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030620,0.000000,0.000000,0.886691,0.587123,0.435193,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.338951,0.000000,0.000000,ATI/Endo

In [5]:
adata_vis.obs.columns.get_loc("training_batch")

56

In [7]:
h5ad_savedir = "h5ad"
os.makedirs(h5ad_savedir, exist_ok=True)

In [ ]:

pbs = []
for library_id in adata_vis.obs["library_id"].unique():
    lib_subset = adata_vis[adata_vis.obs['library_id']==library_id]
    rep_adata = sc.AnnData(X = np.asarray(lib_subset.X.sum(axis = 0)),
                           var = lib_subset.var[[]])
    rep_adata.obs_names = [library_id]
    for i in range(57):
        rep_adata.obs[lib_subset.obs.columns[i]] = lib_subset.obs[lib_subset.obs.columns[i]].iloc[0]
        
    # rep_adata.obs['cond'] = lib_subset.obs['cond'].iloc[0]
    # rep_adata.obs['seq_batch'] = lib_subset.obs['seq_batch'].iloc[0]
    # rep_adata.obs['outcome_24m'] = lib_subset.obs['outcome_24m'].iloc[0]

    pbs.append(rep_adata)

pb = sc.concat(pbs)
pb.write(os.path.join(h5ad_savedir,"pseudobulk_all.h5ad"))

In [9]:
pb

AnnData object with n_obs × n_vars = 44 × 16959
    obs: 'in_tissue', 'array_row', 'array_col', 'library_id', 'alignment', 'desired_rc', 'actual_rc', 'xmin', 'xmax', 'ymin', 'ymax', 'hpx', 'vpx', 'slide', 'area', 'date', 'cytassist_ver', 'seq_batch', 'probe_date', 'probe_lot', 'probe_group', 'cond', 'cond_rep', 'rep', 'age ', 'sex', 'bmi', 'packyears', 'FVC', 'DLCO', '6MWD', 'outcome_long', 'tte_long', 'outcome_24m', 'tte_24m', 'lobe_lr', 'lobe', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'n_counts', 'n_genes', 'training_batch'

In [10]:
pb.obs

,in_tissue,array_row,array_col,library_id,alignment,desired_rc,actual_rc,xmin,xmax,ymin,ymax,hpx,vpx,slide,area,date,cytassist_ver,seq_batch,probe_date,probe_lot,probe_group,cond,cond_rep,rep,age,sex,bmi,packyears,FVC,DLCO,6MWD,outcome_long,tte_long,outcome_24m,tte_24m,lobe_lr,lobe,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,total_counts_ribo,log1p_total_counts_ribo,pct_counts_ribo,total_counts_hb,log1p_total_counts_hb,pct_counts_hb,n_counts,n_genes,training_batch
18_57617_A1,1.0,76.0,22.0,18_57617_A1,auto,75,85,0,0,0,520,14965,14865,V43L25-333,D1,2023-12-06,1.1.5.551,1,2023-09-01,203531,1,IPF,IPF_1,1,77,M,29,10.0,70.0,32.0,413.0,DEAD,23,DEAD,23,left,upper,3961,8.284504,7804.0,8.962520,31.765761,35.212711,39.928242,49.410559,629.0,6.445720,8.059970,0.0,0.0,0.0,0.0,0.000000,0.000000,7804.0,3961,0
20_33940_B2,1.0,0.0,122.0,20_33940_B2,auto,106,106,0,0,30,0,15098,15814,V43B18-389,A1,2024-04-30,1.1.5.551,2,2023-09-01,203531,1,IPF,IPF_2,2,68,M,31,60.0,75.0,42.0,384.0,DEAD,53,ALIVE,24,right,lower,563,6.335054,783.0,6.664409,34.227331,40.868455,53.639847,91.954023,47.0,3.871201,6.002554,0.0,0.0,0.0,0.0,0.000000,0.000000,783.0,563,0
20_24241_A2,1.0,47.0,71.0,20_24241_A2,auto,136,126,0,0,105,0,15701,16871,V43B18-389,D1,2024-04-30,1.1.5.551,2,2023-09-01,203531,1,IPF,IPF_3,3,74,M,28,0.0,68.0,57.0,486.0,ALIVE,53,ALIVE,24,right,middle,6317,8.751158,17779.0,9.785830,16.806345,21.626638,27.768716,39.169807,417.0,6.035481,2.345464,0.0,0.0,0.0,0.0,0.000000,0.000000,17779.0,6317,1
19_35057_C3,1.0,47.0,71.0,19_35057_C3,auto,148,153,0,0,60,0,15244,15788,V43S18-377,A1,2024-05-01,2.0.1.3,2,2024-03-01,203531,1,NSIP,NSIP_1,1,61,M,35,0.0,75.0,55.0,608.0,ALIVE,60,ALIVE,24,right,lower,5099,8.536996,12269.0,9.414912,25.641862,29.497107,34.819464,45.667944,629.0,6.445720,5.126742,0.0,0.0,0.0,0.0,0.000000,0.000000,12269.0,5099,1
20_17688_B2,1.0,47.0,71.0,20_17688_B2,auto,156,165,0,0,50,0,14826,14429,V43S18-377,D1,2024-05-01,2.0.1.3,2,2024-03-02,203531,1,NSIP,NSIP_2,2,67,F,33,27.0,60.0,42.0,463.0,LTx,33,ALIVE,24,right,upper,1360,7.215975,1931.0,7.566311,24.029001,29.777317,39.927499,55.463490,43.0,3.784190,2.226825,0.0,0.0,0.0,0.0,0.000000,0.000000,1931.0,1360,1
20_28197_A1,1.0,0.0,122.0,20_28197_A1,auto,132,156,0,0,0,0,13989,14947,V43S19-398,A1,2024-07-05,2.0.1.3,3,2024-03-03,203531,1,IPF,IPF_4,4,74,F,45,10.0,92.0,54.0,120.0,DEAD,50,ALIVE,24,right,upper,2681,7.894318,4567.0,8.426830,27.983359,31.990366,37.968032,51.105759,157.0,5.062595,3.437705,0.0,0.0,0.0,0.0,0.000000,0.000000,4567.0,2681,0
20_22642_A1,1.0,47.0,71.0,20_22642_A1,auto,140,180,90,0,35,0,15627,14054,V43S19-398,D1,2024-07-05,2.0.1.3,3,2024-03-04,203531,1,NSIP,NSIP_3,3,71,M,38,6.0,79.0,75.0,445.0,ALIVE,53,ALIVE,24,left,middle,409,6.016157,486.0,6.188264,26.131687,36.419753,56.995885,100.000000,13.0,2.639057,2.674897,0.0,0.0,0.0,0.0,0.000000,0.000000,486.0,409,0
20_41501_C1,1.0,47.0,71.0,20_41501_C1,auto,148,204,0,0,90,0,14755,15141,V43B18-391,A1,2024-07-09,2.0.1.3,3,2024-03-05,203531,1,IPF,IPF_5,5,75,M,30,15.0,60.0,38.0,NaN,DEAD,21,DEAD,21,right,upper,1360,7.215975,1827.0,7.510978,19.211823,25.232622,36.179529,52.928298,87.0,4.477337,4.761905,0.0,0.0,0.0,0.0,0.000000,0.000000,1827.0,1360,0
20_33362_C4,1.0,47.0,71.0,20_33362_C4,auto,128,175,0,0,60,0,14549,15104,V43B18-391,D1,2024-07-09,2.0.1.3,3,2024-03-06,203531,1,NSIP,NSIP_4,4,73,M,28,10.0,59.0,NaN,NaN,ALIVE,53,ALIVE,24,right,lower,4187,8.339979,8845.0,9.087721,30.729226,34.516676,39.581685,49.632561,503.0,6.222576,5.686829,0.0,0.0,0.0,0.0,0.000000,0.000000,8845.0,4187,1
20_41847_A1,1.0,47.0,71.0,20_41847_A1,auto,128,151,60,0,0,0,15657,15801,V43B18-282,A1,2024-07-11,2.0.1.3,3,2024-03-07,203531,1,UNC,UNC_1,1,69,M,31,45.0,70.0,63.0,456.0,ALIVE,52,ALIVE,24,left,upper,5743,8.655911,13572.0,9.515838,16.688771,21.566460,27.645152,39.102564,301.0,5.710427,2.217801,0.0,0.0,0.0,0.0,0.000000,0.000000,13572.0,5743,1
20_41615_B1,1.0,47.0,71.0,20_41615_B1,auto,104,132,0,0,0,0,14467,14863,V43B18-282,D1,2024-07-11,2.0.1.3,3,2024-03-08,203531,1,IPF,IPF_6,6,52,M,28,0.0,61.0,50.0,NaN,LTx,36,ALIVE,24,left,upper,4510,8.414274,9239.0,9.131297,24.353285,28.520403,34.008010,44.918281,194.0,5.273000,2.099794,0.0,0.0,0.0,1.0,0.693147,0.010824,9239.0,4510,0
21_06301_B2,1.0,76.0,22.0,21_06301_B2,auto,152,177,0,500,0,480,15785,15334,V43L25-286,A1,2024-07-16,2.0.1.3,3,2024-03-09,203531,1,IPF,IPF_7,7,50,M,26,30.0,50.0,18.0,205.0,ALIVE,48,ALIVE,24,right,middle,2423,7.793174,3265.0,8.091321,14.885145,19.479326,25.849923,41.102603,253.0,5.537334,7.748851,0.0,0.0,0.0,0.0,0.000000,0.000000,3265.0,2423,1
21_05738_A1,1.0,76.0,22.0,21_05738_A1,auto,128,130,0,0,0,0,14496,16455,V43L25-286,D1,2024-07-16,2.0.1.3,3,2024-03-10,203531,1,UNC,UNC_2,2,62,F,42,40.0,88.0,66.0,405.0,ALIVE,48,ALIVE,24,right,upper,1405,7.248504,2034.0,7.618251,24.877089,30.825959,40.658800,55.506391,152.0,5.030438,7.472960,0.0,0.0,0.0,0.0,0.000000,0.000000,2034.0,1405,1
21_57231_A3,1.0,76.0,22.0,21_57231_A3,auto,128,141,0,555,0,490,15913,14786,V43B18-293,A1,2024-07-19,2.0.1.3,3,2024-03-11,203531,1,CHP,CHP_1,1,66,F,24,0.0,84.0,64.0,483.0,ALIVE,39,ALIVE,24,left,upper,975,6.883463,1300.0,7.170888,23.000000,30.692308,40.384615,63.461538,51.0,3.951244,3.923077,0.0,0.0,0.0,0.0,0.000000,0.000000,1300.0,975,1
21_25528_A3,1.0,76.0,22.0,21_25528_A3,auto,108,124,0,0,0,0,14838,15042,V43B18-293,D1,2024-07-19,2.0.1.3,3,2024-03-12,203531,1,UNC,UNC_3,3,53,M,37,20.0,90.0,67.0,503.0,ALIVE,55,ALIVE,24,right,NaN,4844,8.485703,9980.0,9.208439,23.126253,27.144289,32.505010,43.006012,293.0,5.683580,2.935872,0.0,0.0,0.0,1.0,0.693147,0.010020,9980.0,4844,0
22_18446_A1,1.0,76.0,22.0,22_18446_A1,auto,146,166,0,0,0,0,14759,14926,V43S19-393,A1,2024-07-23,2.0.1.3,3,2024-03-13,203531,1,UNC,UNC_4,4,48,F,27,0.0,62.0,54.0,477.0,ALIVE,34,ALIVE,24,right,upper,985,6.893656,1202.0,7.092574,16.971714,25.291181,34.692180,59.650582,46.0,3.850148,3.826955,0.0,0.0,0.0,0.0,0.000000,0.000000,1202.0,985,0
22_18440_A2,1.0,76.0,22.0,22_18440_A2,auto,164,202,0,0,0,0,16259,15232,V43S19-393,D1,2024-07-23,2.0.1.3,3,2024-03-14,203531,1,CHP,CHP_2,2,75,F,41,0.0,66.0,73.0,300.0,ALIVE,34,ALIVE,24,right,upper,2367,7.769801,3399.0,8.131531,14.327743,19.829362,27.596352,45.072080,91.0,4.521789,2.677258,0.0,0.0,0.0,0.0,0.000000,0.000000,3399.0,2367,0
23_15209_A3,1.0,76.0,22.0,23_15209_A3,auto,102,102,100,0,50,0,14780,15926,V43S19-388,A1,2024-08-02,2.0.1.3,4,2024-03-15,203531,1,CHP,CHP_3,3,72,M,27,0.0,116.0,86.0,681.0,ALIVE,25,ALIVE,24,left,upper,6786,8.822764,20515.0,9.928961,17.114307,22.261760,28.876432,40.336339,669.0,6.507277,3.261029,0.0,0.0,0.0,0.0,0.000000,0.000000,20515.0,6786,0
22_50637_A1,1.0,0.0,122.0,22_50637_A1,auto,132,125,0,520,90,0,14576,15073,V43S19-388,D1,2024-08-02,2.0.1.3,4,2024-03-16,203531,1,UNC,UNC_5,5,77,M,26,3.0,90.0,61.0,567.0,DEAD,17,DEAD,17,right,upper,4245,8.353733,7487.0,8.921057,18.231601,22.679311,28.476025,40.029384,294.0,5.686975,3.926806,0.0,0.0,0.0,0.0,0.000000,0.000000,7487.0,4245,0
23_50343_B2,1.0,0.0,122.0,23_50343_B2,auto,114,110,0,0,0,0,15059,15269,V43B18-281,A1,2024-08-13,2.0.1.3,4,2024-03-17,203531,1,CHP,CHP_4,4,72,M,32,33.0,103.0,60.0,459.0,ALIVE,16,ALIVE,16,right,upper,1829,7.512071,2540.0,7.840313,18.346457,24.251969,32.165354,47.677165,81.0,4.406719,3.188976,0.0,0.0,0.0,0.0,0.000000,0.000000,2540.0,1829,1
23_41922_B2,1.0,47.0,71.0,23_41922_B2,auto,120,115,0,500,60,0,14715,16003,V43B18-281,D1,2024-08-13,2.0.1.3,4,2024-03-18,203531,1,CHP,CHP_5,5,66,F,20,0.0,77.0,38.0,505.0,ALIVE,17,ALIVE,17,right,upper,2438,7.799343,3643.0,8.200837,14.658249,20.285479,28.465550,44.935493,62.0,4.143135,1.701894,0.0,0.0,0.0,0.0,0.000000,0.000000,3643.0,2438,1
24_10794_B1,1.0,0.0,122.0,24_10794_B1,auto,122,131,0,0,0,0,15522,15038,V43S18-399,D1,2024-08-20,2.0.1.3,4,2024-03-20,203531,1,UNC,UNC_7,7,47,M,42,30.0,47.0,51.0,NaN,DEAD,4,DEAD,4,right,lower,4646,8.443977,8796.0,9.082166,14.165530,18.804002,25.068213,37.301046,153.0,5.036952,1.739427,0.0,0.0,0.0,0.0,0.000000,0.000000,8796.0,4646,0
20_12743_C1,1.0,76.0,22.0,20_12743_C1,auto,128,120,55,520,90,0,15453,16353,V43S18-380,D1,2024-11-07,2.0.1.3,5,2024-03-21,203531,1,UNC,UNC_8,8,75,M,30,0.0,86.0,63.0,468.0,DEAD,5,DEAD,5,right,lower,2026,7.614312,3085.0,8.034631,18.573744,24.376013,32.350081,50.534846,96.0,4.574711,3.111831,0.0,0.0,0.0,0.0,0.000000,0.000000,3085.0,2026,0
21_55244_B1,1.0,47.0,71.0,21_55244_B1,auto,62,59,0,0,100,500,15825,14672,V43S18-380,A1,2024-11-07,2.0.1.3,5,2024-03-22,203531,1,UNC,UNC_9,9,76,M,31,0.0,105.0,NaN,480.0,ALIVE,39,ALIVE,24,right,middle,5356,8.586159,13769.0,9.530248,30.285424,34.018447,38.949815,48.819813,465.0,6.144186,3.377151,0.0,0.0,0.0,0.0,0.000000,0.000000,13769.0,5356,0
23_45450_A3,1.0,76.0,22.0,23_45450_A3,auto,148,140,60,0,0,0,15176,14594,V43S19-392,D1,2024-11-12,2.0.1.3,5,2024-03-23,203531,1,UNC,UNC_10,10,79,F,20,0.0,62.0,32.0,NaN,DEAD,2,DEAD,2,left,upper,4492,8.410276,10279.0,9.237955,24.292246,29.798619,36.005448,47.280864,314.0,5.752573,3.054772,0.0,0.0,0.0,0.0,0.000000,0.000000,10279.0,4492,1
24_23755_A1,1.0,76.0,22.0,24_23755_A1,auto,164,196,100,0,0,0,15802,15128,V43S19-392,A1,2024-11-12,2.0.1.3,5,2024-03-24,203531,1,UNC,UNC_11,11,68,M,33,5.0,97.0,82.0,NaN,ALIVE,9,ALIVE,9,right,upper,1158,7.055313,1488.0,7.305860,20.295699,27.016129,35.618280,55.779570,113.0,4.736198,7.594086,0.0,0.0,0.0,0.0,0.000000,0.000000,1488.0,1158,0
16_53837_A10,1.0,0.0,122.0,16_53837_A10,auto,130,133,0,0,0,520,15668,15739,V43S19-379,D1,2024-11-13,2.0.1.3,5,2024-03-25,203531,1,UNC,UNC_12,12,64,F,32,18.0,80.0,45.0,300.0,ALIVE,43,ALIVE,24,right,middle,2080,7.640604,2939.0,7.986165,16.910514,22.218442,29.635931,46.240218,163.0,5.099866,5.546104,0.0,0.0,0.0,0.0,0.000000,0.000000,2939.0,2080,0
19_48719_A1,1.0,76.0,22.0,19_48719_A1,auto,128,131,0,0,60,0,15243,15138,V43S18-379,A1,2024-11-13,2.0.1.3,5,2024-03-26,203531,1,UNC,UNC_13,13,67,F,21,0.0,51.0,21.0,NaN,ALIVE,57,ALIVE,24,right,lower,1198,7.089243,2291.0,7.737180,44.740288,49.148843,56.438237,69.532955,74.0,4.317488,3.230031,0.0,0.0,0.0,0.0,0.000000,0.000000,2291.0,1198,0
17_35291_B1,1.0,76.0,22.0,17_35291_B1,auto,166,156,0,500,0,0,14493,14602,V44A08-319,D1,2024-11-19,2.0.1.3,5,2024-07-01,203947,2,UNC,UNC_14,14,60,M,26,26.0,64.0,60.0,NaN,DEAD,48,ALIVE,24,right,lower,1122,7.023759,1468.0,7.292337,19.414169,26.907357,37.193460,57.629428,58.0,4.077538,3.950954,0.0,0.0,0.0,0.0,0.000000,0.000000,1468.0,1122,1
16_46257_A1,1.0,76.0,22.0,16_46257_A1,auto,174,166,0,0,60,0,15027,14645,V44A08-319,A1,2024-11-19,2.0.1.3,5,2024-07-01,203947,2,UNC,UNC_15,15,63,F,39,35.0,60.0,29.0,394.0,LTx,68,ALIVE,24,right,upper,1788,7.489412,2674.0,7.891705,22.849663,28.571429,36.275243,51.832461,152.0,5.030438,5.684368,0.0,0.0,0.0,0.0,0.000000,0.000000,2674.0,1788,0
18_23779_A2,1.0,76.0,22.0,18_23779_A2,auto,136,122,75,490,0,0,14215,15130,V44A22-404,D1,2024-11-20,2.0.1.3,5,2024-07-01,203947,2,UNC,UNC_16,16,67,M,27,2.0,71.0,75.0,305.0,LTx,36,ALIVE,24,left,upper,494,6.204558,599.0,6.396930,25.041736,34.223706,50.918197,100.000000,24.0,3.218876,4.006678,0.0,0.0,0.0,0.0,0.000000,0.000000,599.0,494,1
12_39986_A2,1.0,0.0,122.0,12_39986_A2,auto,172,173,0,0,0,0,14896,15612,V43S18-396,D1,2024-11-15,2.0.1.3,5,2024-03-26,203531,1,UNC,UNC_17,17,62,M,34,NaN,NaN,NaN,NaN,ALIVE,43,ALIVE,24,right,lower,1033,6.941190,1491.0,7.307873,28.504359,35.211268,44.131455,64.252180,162.0,5.093750,10.865191,0.0,0.0,0.0,0.0,0.000000,0.000000,1491.0,1033,0
20_26330_B3,1.0,47.0,71.0,20_26330_B3,auto,54,56,0,480,0,520,14599,15697,V44A22-404,A1,2024-11-20,2.0.1.3,5,2024-07-01,203947,2,NSIP,NSIP_5,5,41,M,39,15.0,38.0,28.0,NaN,DEAD,30,ALIVE,24,right,middle,4286,8.363342,8803.0,9.082961,18.720891,23.753266,30.035215,42.440077,254.0,5.541264,2.885380,0.0,0.0,0.0,0.0,0.000000,0.000000,8803.0,4286,0
21_24837_A1,1.0,47.0,71.0,21_24837_A1,auto,136,145,0,0,0,0,14498,14920,V43S18-396,A1,2024-11-15,2.0.1.3,5,2024-03-26,203531,1,NSIP,NSIP_6,6,19,M,30,0.0,36.0,18.0,401.0,LTx,18,LTx,18,right,upper,5194,8.555452,10885.0,9.295233,15.250345,20.018374,26.017455,37.988057,332.0,5.808143,3.050069,0.0,0.0,0.0,0.0,0.000000,0.000000,10885.0,5194,0
06_30914_A1,1.0,0.0,122.0,06_30914_A1,man,156,145,0,0,0,0,14662,15431,V44A08-344,D1,2024-12-05,2.0.1.3,5,2024-07-01,203947,2,NSIP,NSIP_7,7,61,F,30,NaN,NaN,NaN,NaN,ALIVE,60,ALIVE,24,right,lower,3849,8.255828,6607.0,8.796037,17.314969,21.840472,27.924928,39.957621,326.0,5.789960,4.934161,0.0,0.0,0.0,0.0,0.000000,0.000000,6607.0,3849,0
19_18542_A4,1.0,47.0,71.0,19_18542_A4,auto,104,139,0,0,0,0,15341,15438,V44A08-344,A1,2024-12-05,2.0.1.3,5,2024-07-01,203947,2,NSIP,NSIP_8,8,71,M,21,20.0,103.0,63.0,NaN,DEAD,4,DEAD,4,right,middle,1324,7.189168,1901.0,7.550661,22.461862,29.142557,39.663335,56.654392,23.0,3.178054,1.209890,0.0,0.0,0.0,0.0,0.000000,0.000000,1901.0,1324,1
24_27523_C5,1.0,47.0,71.0,24_27523_C5,auto,100,98,0,0,0,0,15310,15399,V44A08-315,D1,2024-12-06,2.0.1.3,5,2024-07-01,203947,2,CHP,CHP_6,6,59,F,24,0.0,54.0,40.0,386.0,ALIVE,9,ALIVE,9,right,upper,2015,7.608871,3051.0,8.023552,18.813504,24.385447,32.776139,50.344149,61.0,4.127134,1.999344,0.0,0.0,0.0,0.0,0.000000,0.000000,3051.0,2015,0
11_13888_A1,1.0,69.0,7.0,11_13888_A1,auto,110,133,0,0,0,0,15034,15972,V44A08-315,A1,2024-12-06,2.0.1.3,5,2024-07-01,203947,2,CHP,CHP_7,7,67,M,29,40.0,NaN,NaN,NaN,ALIVE,60,ALIVE,24,left,lower,214,5.370638,244.0,5.501258,32.786885,53.278689,94.262295,100.000000,10.0,2.397895,4.098361,0.0,0.0,0.0,0.0,0.000000,0.000000,244.0,214,0
17_25789_B1,1.0,49.0,43.0,17_25789_B1,auto,108,106,0,0,0,0,15070,15176,V44A10-323,D1,2024-12-10,2.0.1.3,5,2024-07-01,203947,2,CHP,CHP_8,8,70,F,28,25.0,56.0,42.0,NaN,DEAD,29,ALIVE,24,right,upper,2394,7.781139,3956.0,8.283241,23.862487,28.538928,35.591507,50.758342,219.0,5.393628,5.535895,0.0,0.0,0.0,0.0,0.000000,0.000000,3956.0,2394,1
08_38774_B2,1.0,47.0,71.0,08_38774_B2,man,82,76,0,0,0,520,14362,15836,V44A10-323,A1,2024-12-10,2.0.1.3,5,2024-07-01,203947,2,CHP,CHP_9,9,73,F,24,20.0,59.0,52.0,270.0,ALIVE,60,ALIVE,24,right,upper,776,6.655440,1016.0,6.924613,25.098425,33.464567,43.307087,72.834646,121.0,4.804021,11.909449,0.0,0.0,0.0,0.0,0.000000,0.000000,1016.0,776,0
16_39724_B1,1.0,47.0,71.0,16_39724_B1,auto,80,74,0,0,0,0,15806,15893,V44A10-304,D1,2024-12-12,2.0.1.3,5,2024-07-01,203947,2,CHP,CHP_10,10,67,M,32,0.0,55.0,42.0,472.0,ALIVE,60,ALIVE,24,right,lower,2493,7.821643,4243.0,8.353262,19.585199,26.231440,34.291775,49.493283,148.0,5.003946,3.488098,0.0,0.0,0.0,0.0,0.000000,0.000000,4243.0,2493,0
21_24095_A3,1.0,0.0,122.0,21_24095_A3,man,186,162,0,0,0,0,15561,15209,V44A10-304,A1,2024-12-12,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_8,8,69,M,36,20.0,83.0,44.0,374.0,ALIVE,42,ALIVE,24,right,NaN,4690,8.453401,8490.0,9.046762,14.899882,19.634865,25.488810,37.279152,220.0,5.398163,2.591284,0.0,0.0,0.0,0.0,0.000000,0.000000,8490.0,4690,0
21_55747_C3,1.0,76.0,22.0,21_55747_C3,man,102,88,0,0,0,0,14028,15291,V44A10-302,D1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_9,9,79,M,23,25.0,65.0,54.0,NaN,ALIVE,38,ALIVE,24,right,lower,5291,8.573952,12297.0,9.417192,17.809222,22.924290,29.381150,41.237700,361.0,5.891644,2.935675,0.0,0.0,0.0,0.0,0.000000,0.000000,12297.0,5291,1
22_16220_B1,1.0,47.0,71.0,22_16220_B1,man,90,91,0,0,0,0,14927,15798,V44A10-302,A1,2024-12-17,2.0.1.3,5,2024-07-01,203947,2,IPF,IPF_10,10,58,F,26,45.0,64.0,39.0,NaN,ALIVE,34,ALIVE,24,right,middle,5863,8.676587,14405.0,9.575400,18.153419,23.533495,29.552239,40.631725,469.0,6.152733,3.255814,0.0,0.0,0.0,0.0,0.000000,0.000000,14405.0,5863,1